events {}

http {
    upstream products_service {
        server products-service:5000;
    }

    upstream orders_service {
        server orders-service:5000;
    }

    upstream customers_service {
        server customers-service:5000;
    }

    server {
        listen 80;

        location /products/ {
            proxy_pass http://products_service/;
        }

        location /orders/ {
            proxy_pass http://orders_service/;
        }

        location /customers/ {
            proxy_pass http://customers_service/;
        }

        location / {
            return 200 '{"message":"NGINX API Gateway is running","services":["/products/","/orders/","/customers/"]}';
            add_header Content-Type application/json;
        }
    }
}